# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=250)),
                ('date', models.IntegerField()),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
    ]
